name: Cheshire Spray Painting Ltd.
favicon: null
layout_spectrum: 0.54456
typography_spectrum: 0.56074
title: Cheshire Paint Spraying - Macclesfield
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#434a50'
    - '#8a8985'
    - '#050505'
    - '#ffffff'
    - '#ffff00'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.028032816480845213
  rhythmicContrast: 0.75
purpose: []
