name: Cheshire Spray Painting Ltd.
favicon: null
layout_spectrum: 0.14664
typography_spectrum: 0.56074
title: Cheshire Paint Spraying ltd. - Macclesfield
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75890628-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#887867'
    - '#532202'
    - '#326000'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
