typography_spectrum: 0.56074
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#010101'
    - '#9ccd1c'
    - '#676767'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.69237
analytics:
  google: UA-75890628-1
  facebook: null
  twitter: null
name: Cheshire Spray Painting Ltd.
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: "Cheshire Paint Spraying ltd. \_Macclesfield - 07857 133 204"
purpose: []
