typography_spectrum: 0.56074
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#010101'
    - '#9ccd1c'
    - '#676767'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.69237
analytics:
  google: UA-75890628-1
  facebook: null
  twitter: null
name: Cheshire Spray Painting Ltd.
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact Us
    id: ccd8d838-92a4-45b8-9aef-027fdffc7788
    type: content
  - name: New Kitchens & Re-Sprays.
    id: eec7424d-1bb1-4e2f-9b18-f26640bc7fc1
    type: content
  - name: Windows
    id: e2b9a528-f56a-43b1-97c3-1337a179b766
    type: content
favicon: null
title: "Cheshire Spray Painting ltd.\_"
description: In Home/On Site/Spray Shop
purpose: []
