name: Cheshire Spray Painting Ltd.
favicon: null
layout_spectrum: 0.54456
typography_spectrum: 0.74191
title: Cheshire Paint Spraying - Macclesfield
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#180e0f'
    - '#bcad98'
    - '#95734c'
    - '#67ad77'
  brandStrength: 0.25
  lightness: 0.8215786644723266
  saturation: 0.028032816480845213
  rhythmicContrast: 0.75
purpose: []
