name: Cheshire Spray Painting Ltd.
favicon: null
layout_spectrum: 0.2585
typography_spectrum: 0.56074
title: Cheshire Paint Spraying ltd. - Macclesfield - 07857 133 204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75890628-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#010101'
    - '#9ccd1c'
    - '#676767'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
